services:
  - type: web
    name: wati-free-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install --with-deps chromium
    startCommand: python main.py
